spring:
  profiles:
    include: db, jwt

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    miniProject: debug

server:
  servlet:
    session:
      tracking-modes: cookie